# .github/workflows/issues_prs_management.yml
name: Issue & PR Management
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
jobs:
  manage:
    runs-on: ubuntu-latest
    steps:
      - name: Auto-label PRs
        uses: actions/labeler@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Comment with PR author's name
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Thanks for the PR, @${{ github.event.pull_request.user.login }}! We will review it soon.`
            });
            
      - name: Handle stale issues/PRs
        uses: actions/stale@main
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          days-before-stale: 60
          days-before-close: 7
